// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrh_pSOINqvrfkddEvL_h7ZWq19tgbo4',
    appId: '1:308105564646:web:df6c9e8efbe9559dd58627',
    messagingSenderId: '308105564646',
    projectId: 'travel2-24f09',
    authDomain: 'travel2-24f09.firebaseapp.com',
    storageBucket: 'travel2-24f09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4BFDdaY64yH5zjxmrJHK5-V2NegKIWc',
    appId: '1:308105564646:android:27d6a0b19c70a037d58627',
    messagingSenderId: '308105564646',
    projectId: 'travel2-24f09',
    storageBucket: 'travel2-24f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF9ALO9jf1TGsoXxsdKB6HB6yEEnUCDJA',
    appId: '1:308105564646:ios:6aeed016c483e26dd58627',
    messagingSenderId: '308105564646',
    projectId: 'travel2-24f09',
    storageBucket: 'travel2-24f09.appspot.com',
    iosBundleId: 'com.example.travel2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF9ALO9jf1TGsoXxsdKB6HB6yEEnUCDJA',
    appId: '1:308105564646:ios:6f6866a3249cf248d58627',
    messagingSenderId: '308105564646',
    projectId: 'travel2-24f09',
    storageBucket: 'travel2-24f09.appspot.com',
    iosBundleId: 'com.example.travel2.RunnerTests',
  );
}
